### PR TITLE
Visible small percentages

### PR DESCRIPTION
**Pull request by mattyhead**
Bumps the percentage display outside of the bar when it gets smaller than 12%, so that it remains visible.

### CODE REVIEW

**Comment by mattyhead** [comment]
@timwis, on review, this is not a responsive solution.  On slimmer screens, in-bar percentages can get clipped -- which was the problem I was asked to solve.  Sigh.  It also doesn't account for small race-level bars at all (my test data is, naturally, kind of fat).  I'm off to muck about with the node code for now.  I'll have to take a second pass at this after I fatten up the data still more, so maybe I'll have time to do this better then.  Still, it does improve the visibility of the percentages, in general.

**Comment by timwis** [comment]
Hey @mattyhead - it is technically responsive, but it may have an alignment issue or two that we weren't able to knock out in the few hours we worked on it on election day. Nothing we can't fix in another few hours, and @KClough @laurenancona @mjumbewu and I would be happy to help I'm sure. Is this the Matt from the City Commissioners Office that I met? (Didn't get the last name)

**Comment by mattyhead** [comment]
Yup. Elections Matt Murphy.  Yes, the original code is responsive... I mean
what I did didn't solve the problem (hidden small percentages on smaller
displays) Seth asked me to fix a couple of days ago.

**Comment by mattyhead** [comment]
BTW, thanks for bringing up Cloud9.  I LOVE it.

**Comment by timwis** [comment]
Awesome! I'm at CodeForPhilly right now and just reviewing the commits - changes look good, nice job!

**Pull request merged**
